import Head from "next/head";
import Image from "next/image";
import bg from "../public/images/bad-weather.jpg";
import { useState } from "react";

import SearchForm from "../components/SearchForm";
import Weather from "../components/Weather/Weather";
import LoadingSpinner from "../components/ui/LoadingSpinner";
import Container from "../components/ui/Container";
import Layout from "../components/ui/layout";

export default function Home() {
  const [weather, setWeather] = useState({});
  const [city, setCity] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [hasError, setHasError] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=999c6ee311cf78c9e96aa7336da0796f`;

  const handleSearch = (event) => {
    event.preventDefault();

    const fetchWeather = async () => {
      setIsLoading(true);
      const response = await fetch(url);

      if (!response.ok) {
        throw new Error(error);
      }

      const responseData = await response.json();
      setWeather(responseData);
      setIsLoading(false);
    };

    try {
      fetchWeather();
    } catch (error) {
      setHasError(true);
      setError(
        error || "Something went wrong. Did you searched for a real city?"
      );
      console.log(error);
    }
  };

  const handleCityChange = (event) => {
    setCity(event.target.value);
  };

  return (
    <div>    
      <Head>
        <title>Weather - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <Layout>

      
      {/* Search */}
      <Container>
        <SearchForm onCityChange={handleCityChange} onSearch={handleSearch} />
      </Container>
      

      {/* Weather */}
      <Container>
        {isLoading && <LoadingSpinner/>}
        {weather.main && <Weather weatherData={weather}/>}
      </Container>
      
      </Layout>
    </div>
  );
}
{/*Background Image */}
<Image
src={bg}
alt="Weather Background"
layout="fill"
className="object-cover"
/>
